### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Masternumber155** [berkayylmao/berkayylmao.github.io#1]
Hey man, you prolly aren't gonna speak to me and this isn't really the place for it, but I've done some research and was curious if the NFS chat choas mod was open for the public or only reserved for Kuru. I don't know if you guys have a deal or something but I was interested in using it. Please let me know. Thanks in advance

**Comment by berkayylmao** [comment]
Why would you feel like I wouldn't speak to you? I don't even know who you are.

Anyway, the NFS chaos mod was public but I had to take it down because of licensing. The updated version will be made public again once it's finished. It's going to take some time though.

**Comment by Masternumber155** [comment]
Alright, thanks for that. I was just curious about it, that's all, I appreciate it. You have a wonderful day
